### ISSUE TITLE
gitignore: README: Added gitignore, updated readme

### ISSUE THREAD

**Issue by RudraNilBasu** [djmgit/PlotIt#1]
Patch link: https://pastebin.com/kN4Nxqqq

Corrected:
 
```
  Uing => Using
```
 
Example implementations:
 
```
  python plotit -f sin(x)
```

to

``` 
  python plotit -f 'sin(x)'
```
 
Added gitignore to ignore *.pyc files from being tracked by git

**Comment by RudraNilBasu** [comment]
Updated patch: https://pastebin.com/nF6EAxW6

Usage / Examples: 

Additionally changed:
```
python plotit ...
```

to 

```
python plotit.py
```

**Comment by djmgit** [comment]
@RudraNilBasu thanks for working on this :)
