### ISSUE TITLE
Add try catch block in lib/plotutil.py

### ISSUE THREAD

**Issue by djmgit** [djmgit/PlotIt#19]
Surround plt.plot() present in lib/plotlib.py with try-catch block, so that if matplotlib raises any exception, our app does not terminate abruptly. Rather the reason for which matplotlib failed to plot the graph should be displayed in the terminal and the user should be able to continue using the app.

**Comment by ash13** [comment]
https://github.com/djmgit/PlotIt/pull/23

Hi , let me know if this works. Let me know if needed to improve.

**Comment by djmgit** [comment]
@ash13 Thanks for working on this. Next time please refer the corresponding issue in your PR.
Refer to CONTRIBUTING.md if required. :)
