### ISSUE TITLE
Add support for math functions

### ISSUE THREAD

**Issue by djmgit** [djmgit/PlotIt#4]
Presently the application provides support for only sin, cos and exp math functions. We need to add support for other functions as well. Python math module contains  a lot of functions, so it will be very tedious to add support for all of them at once. We can start by a few popular and commonly used functions like
```
log, 
sinh,
cosh,
pi(constant),
sqrt,
abs
```

**Comment by RudraNilBasu** [comment]
Implemented few basic functions including:
* sqrt()
* factorial()
* pi
* e

Patch link: https://pastebin.com/3ySmydgt

**Comment by djmgit** [comment]
@RudraNilBasu thanks for working on this :+1: 
I have merged the provided patch.
So the remaining functions are:
```
log
sinh
cosh
abs
```

**Comment by Aniq55** [comment]
Major changes required, we might not need the current procedure.
