### ISSUE TITLE
[PATCH] gitignore: Add .temp/ in gitignore

### ISSUE THREAD

**Issue by RudraNilBasu** [djmgit/PlotIt#8]
Patch Link: https://pastebin.com/MafKix5X

Added .temp/ in gitignore so that it is not tracked
by git whenever a new GUI graph is plotted

As a result, if the .temp/ folder is not already created
an error will be thrown at:

```
  plt.savefig(".temp/generated_plot.png")
```

which is fixed by checking and creating the directory if
not already created:

```
  if not os.path.exists('.temp/'):
    os.mkdir('.temp/')
```

**Comment by djmgit** [comment]
@RudraNilBasu Thanks for working on this :+1:
